[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Handle language redirects
[[redirects]]
  from = "/"
  to = "/en"
  status = 302
  conditions = {Language = ["en"]}

[[redirects]]
  from = "/"
  to = "/es"
  status = 302
  conditions = {Language = ["es"]}

[[redirects]]
  from = "/"
  to = "/de"
  status = 302
  conditions = {Language = ["de"]}

[[redirects]]
  from = "/"
  to = "/ja"
  status = 302
  conditions = {Language = ["ja"]}

# Fallback redirect to English
[[redirects]]
  from = "/"
  to = "/en"
  status = 302 