[build]
  command = "npm run netlify-build"
  publish = "out"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"

# Language-specific redirects for root
[[redirects]]
  from = "/"
  to = "/en/"
  status = 302
  conditions = {Language = ["en"]}

[[redirects]]
  from = "/"
  to = "/es/"
  status = 302
  conditions = {Language = ["es"]}

[[redirects]]
  from = "/"
  to = "/de/"
  status = 302
  conditions = {Language = ["de"]}

[[redirects]]
  from = "/"
  to = "/ja/"
  status = 302
  conditions = {Language = ["ja"]}

# Fallback redirect to English
[[redirects]]
  from = "/"
  to = "/en/"
  status = 302

# Handle contact page redirects
[[redirects]]
  from = "/contact"
  to = "/en/contact"
  status = 302
  conditions = {Language = ["en"]}

[[redirects]]
  from = "/contact"
  to = "/es/contact"
  status = 302
  conditions = {Language = ["es"]}

[[redirects]]
  from = "/contact"
  to = "/de/contact"
  status = 302
  conditions = {Language = ["de"]}

[[redirects]]
  from = "/contact"
  to = "/ja/contact"
  status = 302
  conditions = {Language = ["ja"]}

# Default contact page fallback
[[redirects]]
  from = "/contact"
  to = "/en/contact"
  status = 302

# SPA fallbacks for each language
[[redirects]]
  from = "/en/*"
  to = "/en/index.html"
  status = 200

[[redirects]]
  from = "/es/*"
  to = "/es/index.html"
  status = 200

[[redirects]]
  from = "/de/*"
  to = "/de/index.html"
  status = 200

[[redirects]]
  from = "/ja/*"
  to = "/ja/index.html"
  status = 200 